import { BusLine } from './types';

// Common Intermediates to reuse
const INT_STO_AMARO = ['SOCORRO', 'LARGO 13', 'AV. STO. AMARO', 'BORBA GATO'];
const INT_JOAO_DIAS = ['CENTRO EMPRESARIAL', 'PTE. JOÃO DIAS', 'GIOVANNI GRONCHI'];
const INT_BANDEIRA = ['AV. 9 DE JULHO', 'ITAIM BIBI', 'JARDINS', 'AV. BRASIL'];
const INT_CENTRO = ['ANHANGABAÚ', '23 DE MAIO', 'PÇA. DA SÉ'];
const INT_MARGINAL = ['PTE. SOCORRO', 'MARGINAL PINHEIROS', 'EST. ITAPECERICA'];

export const BUS_LINES: BusLine[] = [
  // 5xxx Lines
  {
    id: '5119',
    lineNumber: '5119-10',
    destination: 'LGO. SÃO FRANCISCO',
    secondaryDestination: 'JD. IRENE',
    intermediateDestinations: ['TERM. CAPELINHA', 'EST. ITAPECERICA', 'AV. IBRAPUERA', 'BRIGADEIRO'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-5119',
    description: 'Padron Millennium',
    history: 'Ligação troncal histórica da Zona Sul.',
    viaSign: 'VIA IBIRAPUERA',
    itinerary: ["EST. ITAPECERICA", "TERM. CAPELINHA", "AV. IBIRAPUERA", "LGO. SÃO FRANCISCO"]
  },
  {
    id: '5338-10',
    lineNumber: '5338-10',
    destination: 'LGO. SÃO FRANCISCO',
    secondaryDestination: 'VALO VELHO',
    intermediateDestinations: ['RIO BONITO', 'SOCORRO', 'AV. STO. AMARO', 'ITAIM'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1998',
    plate: 'CPB-5338',
    description: 'Articulado',
    history: 'Linha longa via Rio Bonito.',
    viaSign: 'VIA RIO BONITO',
  },
  {
    id: '5338-22',
    lineNumber: '5338-22',
    destination: 'LGO. SÃO FRANCISCO',
    secondaryDestination: 'JD. GUARUJÁ',
    intermediateDestinations: ['AV. GUARAPIRANGA', 'SOCORRO', 'AV. STO. AMARO'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-2200',
    description: 'Convencional',
    history: 'Atendimento específico do Jd. Guarujá.',
    viaSign: 'VIA SOCORRO',
  },
  
  // 6xxx Lines - Grupo Santo Amaro (Destino: Santo Amaro)
  {
    id: '6002',
    lineNumber: '6002-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'JD. STO. EDUARDO',
    intermediateDestinations: ['EST. ITAPECERICA', 'PTE. JOÃO DIAS'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2001',
    plate: 'TKB-6002',
    description: 'Urbanuss Pluss',
    history: 'Alimentadora importante da região do Itap. da Serra.',
    viaSign: 'VIA ITAPECERICA',
  },
  {
    id: '6042',
    lineNumber: '6042-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'PQ. REGINA',
    intermediateDestinations: ['CAMPO LIMPO', 'JOÃO DIAS'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6042',
    description: 'Apache Vip',
    history: 'Linha de bairro.',
    viaSign: 'VIA CAMPO LIMPO',
  },
  {
    id: '6044',
    lineNumber: '6044-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'JD. STO. EDUARDO',
    intermediateDestinations: ['M' + 'B' + 'OI MIRIM', 'LARGO 13'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6044',
    description: 'Monobloco O-371',
    history: 'Rota tradicional via M\'Boi Mirim.',
    viaSign: 'VIA M\'BOI MIRIM',
  },
  {
    id: '6046',
    lineNumber: '6046-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'PQ. FERNANDA',
    intermediateDestinations: ['VALO VELHO', 'JOÃO DIAS'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-6046',
    description: 'Apache S21',
    history: 'Atendimento ao Parque Fernanda.',
    viaSign: 'VIA JOÃO DIAS',
  },
  {
    id: '6047',
    lineNumber: '6047-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'JD. STO. EDUARDO',
    intermediateDestinations: ['UNASP', 'EST. ITAPECERICA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2003',
    plate: 'TKB-6047',
    description: 'Millennium II',
    history: 'Via Unasp.',
    viaSign: 'VIA UNASP',
  },
  {
    id: '6048-10',
    lineNumber: '6048-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'JD. SÃO BENTO',
    intermediateDestinations: ['CAPÃO REDONDO', 'LARGO 13'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1998',
    plate: 'CPB-6048',
    description: 'Vitória',
    history: 'Linha carregada do Capão.',
    viaSign: 'VIA CAPÃO',
  },
  {
    id: '6048-21',
    lineNumber: '6048-21',
    destination: 'SANTO AMARO',
    secondaryDestination: 'CAPÃO REDONDO',
    intermediateDestinations: ['COHAB', 'JOÃO DIAS'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2001',
    plate: 'CPB-4821',
    description: 'Alpha',
    history: 'Atendimento reforço.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6048-51',
    lineNumber: '6048-51',
    destination: 'SANTO AMARO',
    secondaryDestination: 'JD. SÃO BENTO',
    intermediateDestinations: ['DIRETO', 'MARGINAL'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-4851',
    description: 'S21',
    history: 'Linha expressa nas manhãs.',
    viaSign: 'EXPRESSO',
  },
  {
    id: '6049-10',
    lineNumber: '6049-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'VALO VELHO',
    intermediateDestinations: ['ITAPECERICA', 'CENTRO EMPRESARIAL'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6049',
    description: 'Apache Vip',
    history: 'Ligação Valo Velho x Sto Amaro.',
    viaSign: 'VIA ITAPECERICA',
  },
  {
    id: '6049-51',
    lineNumber: '6049-51',
    destination: 'SANTO AMARO',
    secondaryDestination: 'VALO VELHO',
    intermediateDestinations: ['DIRETO', 'JOÃO DIAS'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-4951',
    description: 'Apache Vip',
    history: 'Reforço horário de pico.',
    viaSign: 'VIA JOÃO DIAS',
  },
  {
    id: '6052',
    lineNumber: '6052-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'JD. DAS ROSAS',
    intermediateDestinations: ['CAPÃO REDONDO', 'LARGO 13'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1997',
    plate: 'CPB-6052',
    description: 'Torino GV',
    history: 'Atendimento local.',
    viaSign: 'VIA CAPÃO',
  },
  
  // Grupo Terminal João Dias
  {
    id: '6055',
    lineNumber: '6055-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'JD. IBIRAPUERA',
    intermediateDestinations: ['CENESP', 'MARGINAL'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2001',
    plate: 'CPB-6055',
    description: 'Millennium',
    history: 'Ligação curta ao terminal.',
    viaSign: 'VIA CENESP',
  },
  {
    id: '6056',
    lineNumber: '6056-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'JD. CAPELINHA',
    intermediateDestinations: ['COHAB ADVENTISTA', 'EST. ITAPECERICA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6056',
    description: 'Apache Vip',
    history: 'Alimentadora do TJD.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6057',
    lineNumber: '6057-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'PQ. ARARIBÁ',
    intermediateDestinations: ['CAMPO LIMPO', 'EST. ITAPECERICA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2000',
    plate: 'TKB-6057',
    description: 'Alpha',
    history: 'Linha do Araribá.',
    viaSign: 'VIA C. LIMPO',
  },
  {
    id: '6058',
    lineNumber: '6058-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'JD. OLINDA',
    intermediateDestinations: ['CAMPO LIMPO', 'EST. ITAPECERICA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2003',
    plate: 'TKB-6058',
    description: 'Millennium',
    history: 'Região do Campo Limpo.',
    viaSign: 'VIA C. LIMPO',
  },
  {
    id: '6059',
    lineNumber: '6059-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'JD. LÍDIA',
    intermediateDestinations: ['CAPÃO REDONDO', 'EST. ITAPECERICA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6059',
    description: 'S21',
    history: 'Alimentadora.',
    viaSign: 'VIA CAPÃO',
  },
  {
    id: '6062',
    lineNumber: '6062-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'JD. COMERCIAL',
    intermediateDestinations: ['COHAB', 'CENESP'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6062',
    description: 'Apache',
    history: 'Linha via Cohab.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6063',
    lineNumber: '6063-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'PQ. FERNANDA',
    intermediateDestinations: ['VALO VELHO', 'ITAPECERICA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1998',
    plate: 'CPB-6063',
    description: 'Vitória',
    history: 'Opção ao Parque Fernanda.',
    viaSign: 'VIA VALO VELHO',
  },
  {
    id: '6064',
    lineNumber: '6064-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'PQ. FERNANDA',
    intermediateDestinations: ['JD. SÃO BENTO', 'ITAPECERICA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1998',
    plate: 'CPB-6064',
    description: 'Vitória',
    history: 'Variação via Jd. São Bento.',
    viaSign: 'VIA SÃO BENTO',
  },
  {
    id: '6065',
    lineNumber: '6065-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'COHAB ADVENTISTA',
    intermediateDestinations: ['CENESP', 'ITAPECERICA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2001',
    plate: 'TKB-6065',
    description: 'Pluss',
    history: 'Ligação Cohab x Terminal.',
    viaSign: 'VIA CENESP',
  },

  // Grupo Represa / Centro
  {
    id: '6095',
    lineNumber: '6095-10',
    destination: 'REPRESA',
    secondaryDestination: 'JD. IBIRAPUERA',
    intermediateDestinations: ['JOÃO DIAS', 'GUARAPIRANGA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6095',
    description: 'Alpha',
    history: 'Linha local da represa.',
    viaSign: 'VIA REPRESA',
  },
  {
    id: '6096',
    lineNumber: '6096-10',
    destination: 'REPRESA',
    secondaryDestination: 'JD. SÃO LUIZ',
    intermediateDestinations: ['GUARAPIRANGA', 'SOCORRO'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6096',
    description: 'Vitória',
    history: 'Atendimento São Luiz.',
    viaSign: 'VIA SÃO LUIZ',
  },
  {
    id: '6097',
    lineNumber: '6097-10',
    destination: 'REPRESA',
    secondaryDestination: 'JD. CAPELINHA',
    intermediateDestinations: ['EST. ITAPECERICA', 'GUARAPIRANGA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2001',
    plate: 'TKB-6097',
    description: 'Pluss',
    history: 'Linha Jd. Capelinha.',
    viaSign: 'VIA GUARAPIRANGA',
  },
  
  // Linhas 609F (Princesa Isabel / Anhangabaú)
  {
    id: '609F-10',
    lineNumber: '609F-10',
    destination: 'PÇA. PRINC. ISABEL',
    secondaryDestination: 'CHÁC. SANTANA',
    intermediateDestinations: ['AV. STO. AMARO', '9 DE JULHO', 'AMARAL GURGEL'],
    companyName: 'Viação Gatusa',
    companyLogoText: 'GATUSA',
    color: '#7f1d1d',
    year: '2003',
    plate: 'GTS-609F',
    description: 'Millennium',
    history: 'Linha longa cruzando a cidade.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '609F-21',
    lineNumber: '609F-21',
    destination: 'ANHANGABAÚ',
    secondaryDestination: 'CHÁC. SANTANA',
    intermediateDestinations: ['AV. STO. AMARO', '9 DE JULHO', 'BANDEIRA'],
    companyName: 'Viação Gatusa',
    companyLogoText: 'GATUSA',
    color: '#7f1d1d',
    year: '2003',
    plate: 'GTS-9F21',
    description: 'Millennium',
    history: 'Encurtamento no centro.',
    viaSign: 'VIA 9 DE JULHO',
  },

  {
    id: '6315',
    lineNumber: '6315-10',
    destination: 'BRIGADEIRO',
    secondaryDestination: 'JD. GUARUJÁ',
    intermediateDestinations: ['SOCORRO', 'STO. AMARO', 'IBIRAPUERA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1998',
    plate: 'CPB-6315',
    description: 'Articulado',
    history: 'Antiga linha tronco.',
    viaSign: 'VIA IBIRAPUERA',
  },

  // Grupo Bandeira / Centro (Eixo 9 de Julho / Santo Amaro)
  {
    id: '6402',
    lineNumber: '6402-10',
    destination: 'ITAIM',
    secondaryDestination: 'TERM. JOÃO DIAS',
    intermediateDestinations: ['AV. STO. AMARO', 'JOÃO DIAS'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2002',
    plate: 'CPB-6402',
    description: 'Apache S21',
    history: 'Ligação Terminal ao Itaim Bibi.',
    viaSign: 'VIA STO. AMARO',
  },
  {
    id: '6433',
    lineNumber: '6433-10',
    destination: 'PÇA. DA BANDEIRA',
    secondaryDestination: 'JD. IBIRAPUERA',
    intermediateDestinations: INT_BANDEIRA,
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-6433',
    description: 'Millennium',
    history: 'Via Nove de Julho.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '6435',
    lineNumber: '6435-10',
    destination: 'TERM. BANDEIRA',
    secondaryDestination: 'PQ. STO. ANTÔNIO',
    intermediateDestinations: ['JOÃO DIAS', 'STO. AMARO', '9 DE JULHO'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6435',
    description: 'Pluss',
    history: 'Linha forte do Pq. Sto. Antônio.',
    viaSign: 'VIA JOÃO DIAS',
  },
  {
    id: '6441',
    lineNumber: '6441-10',
    destination: 'PÇA. DA BANDEIRA',
    secondaryDestination: 'JD. INGÁ',
    intermediateDestinations: INT_BANDEIRA,
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6441',
    description: 'Alpha',
    history: 'Jd. Ingá ao Centro.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '6442',
    lineNumber: '6442-10',
    destination: 'PÇA. DA BANDEIRA',
    secondaryDestination: 'PQ. ARARIBÁ',
    intermediateDestinations: INT_BANDEIRA,
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2001',
    plate: 'TKB-6442',
    description: 'Apache Vip',
    history: 'Araribá ao Centro.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '6443',
    lineNumber: '6443-10',
    destination: 'PÇA. DA BANDEIRA',
    secondaryDestination: 'JD. CAPELINHA',
    intermediateDestinations: INT_BANDEIRA,
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2002',
    plate: 'CPB-6443',
    description: 'S21',
    history: 'Capelinha ao Centro.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '6445',
    lineNumber: '6445-10',
    destination: 'PÇA. DA BANDEIRA',
    secondaryDestination: 'JD. OLINDA',
    intermediateDestinations: INT_BANDEIRA,
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2001',
    plate: 'TKB-6445',
    description: 'Pluss',
    history: 'Jd. Olinda ao Centro.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '6450',
    lineNumber: '6450-10',
    destination: 'TERM. BANDEIRA',
    secondaryDestination: 'TERM. CAPELINHA',
    intermediateDestinations: ['TERM. JOÃO DIAS', 'STO. AMARO', '9 DE JULHO'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1995',
    plate: 'CPB-6450',
    description: 'Articulado',
    history: 'Troncal pesada do corredor.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '6453',
    lineNumber: '6453-10',
    destination: 'PÇA. DA BANDEIRA',
    secondaryDestination: 'JD. LÍDIA',
    intermediateDestinations: INT_BANDEIRA,
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-6453',
    description: 'S21',
    history: 'Jd. Lídia ao Centro.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '6454',
    lineNumber: '6454-10',
    destination: 'LGO. SÃO FRANCISCO',
    secondaryDestination: 'TERM. CAPELINHA',
    intermediateDestinations: ['STO. AMARO', '23 DE MAIO', 'PÇA. DA SÉ'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6454',
    description: 'Millennium',
    history: 'Via 23 de Maio.',
    viaSign: 'VIA 23 DE MAIO',
  },
  {
    id: '6466',
    lineNumber: '6466-10',
    destination: 'TERM. BANDEIRA',
    secondaryDestination: 'JD. COMERCIAL',
    intermediateDestinations: INT_BANDEIRA,
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6466',
    description: 'Apache',
    history: 'Jd. Comercial ao Centro.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '6496',
    lineNumber: '6496-10',
    destination: 'PÇA. DA BANDEIRA',
    secondaryDestination: 'COHAB ADVENTISTA',
    intermediateDestinations: INT_BANDEIRA,
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2001',
    plate: 'TKB-6496',
    description: 'Pluss',
    history: 'Cohab ao Centro.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '6498',
    lineNumber: '6498-10',
    destination: 'PÇA. DA BANDEIRA',
    secondaryDestination: 'PQ. FERNANDA',
    intermediateDestinations: INT_BANDEIRA,
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1998',
    plate: 'CPB-6498',
    description: 'Vitória',
    history: 'Pq. Fernanda ao Centro.',
    viaSign: 'VIA 9 DE JULHO',
  },
  {
    id: '6499',
    lineNumber: '6499-10',
    destination: 'PÇA. DA BANDEIRA',
    secondaryDestination: 'VALO VELHO',
    intermediateDestinations: INT_BANDEIRA,
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6499',
    description: 'Apache Vip',
    history: 'Valo Velho ao Centro.',
    viaSign: 'VIA 9 DE JULHO',
  },

  // Outros
  {
    id: '675I',
    lineNumber: '675I-10',
    destination: 'METRÔ SÃO JUDAS',
    secondaryDestination: 'JD. INGÁ',
    intermediateDestinations: ['CENESP', 'JOÃO DIAS', 'AEROPORTO'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2001',
    plate: 'CPB-675I',
    description: 'S21',
    history: 'Ligação perimetral importante.',
    viaSign: 'VIA AEROPORTO',
  },

  // Grupo 68xx (Alimentadoras Terminal Capelinha / João Dias)
  {
    id: '6801',
    lineNumber: '6801-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'JD. IBIRAPUERA',
    intermediateDestinations: INT_JOAO_DIAS,
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-6801',
    description: 'Alpha',
    history: 'Alimentadora TJD.',
    viaSign: 'VIA CENESP',
  },
  {
    id: '6803',
    lineNumber: '6803-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'JD. CAPELINHA',
    intermediateDestinations: ['COHAB', 'ITAPECERICA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6803',
    description: 'Vitória',
    history: 'Ligação Capelinha x João Dias.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6804',
    lineNumber: '6804-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'JD. INGÁ',
    intermediateDestinations: ['VALO VELHO', 'ITAPECERICA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-6804',
    description: 'S21',
    history: 'Alimentadora TJD.',
    viaSign: 'VIA ITAPECERICA',
  },
  {
    id: '6805',
    lineNumber: '6805-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'PQ. STO. ANTÔNIO',
    intermediateDestinations: ['JOÃO DIAS', 'CENESP'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6805',
    description: 'Pluss',
    history: 'Pq. Sto Antônio x João Dias.',
    viaSign: 'VIA CENESP',
  },
  
  // Alimentadoras Terminal Capelinha
  {
    id: '6813',
    lineNumber: '6813-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'JD. LÍDIA',
    intermediateDestinations: ['COHAB', 'CAMPO LIMPO'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1998',
    plate: 'CPB-6813',
    description: 'Vitória',
    history: 'Alimentadora TC.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6814',
    lineNumber: '6814-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'CAMPO LIMPO',
    intermediateDestinations: ['JD. HELGA', 'PIRAJUSSARA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2001',
    plate: 'TKB-6814',
    description: 'Apache',
    history: 'Ligação Campo Limpo x Capelinha.',
    viaSign: 'VIA HELGA',
  },
  {
    id: '6815',
    lineNumber: '6815-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'JD. COMERCIAL',
    intermediateDestinations: ['COHAB', 'ITAPECERICA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6815',
    description: 'Pluss',
    history: 'Alimentadora TC.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6816',
    lineNumber: '6816-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'JD. MITSUTANI',
    intermediateDestinations: ['PIRAJUSSARA', 'EST. ITAPECERICA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6816',
    description: 'Apache Vip',
    history: 'Via Mitsutani.',
    viaSign: 'VIA PIRAJUSSARA',
  },
  {
    id: '6817',
    lineNumber: '6817-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'JD. SÃO BENTO',
    intermediateDestinations: ['CAPÃO REDONDO', 'COHAB'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6817',
    description: 'S21',
    history: 'Alimentadora TC.',
    viaSign: 'VIA CAPÃO',
  },
  {
    id: '6818',
    lineNumber: '6818-10',
    destination: 'TERM. JOÃO DIAS',
    secondaryDestination: 'JD. V. DAS VIRTUDES',
    intermediateDestinations: ['CAPÃO REDONDO', 'CENESP'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-6818',
    description: 'S21',
    history: 'Alimentadora TJD.',
    viaSign: 'VIA CAPÃO',
  },
  {
    id: '6820-10',
    lineNumber: '6820-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'JD. DAS ROSAS',
    intermediateDestinations: ['COHAB', 'ITAPECERICA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1998',
    plate: 'CPB-6820',
    description: 'Vitória',
    history: 'Alimentadora TC.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6820-31',
    lineNumber: '6820-31',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'JD. DAS ROSAS',
    intermediateDestinations: ['DIRETO', 'CORREDOR'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1998',
    plate: 'CPB-2031',
    description: 'Vitória',
    history: 'Atendimento pico.',
    viaSign: 'VIA CORREDOR',
  },
  {
    id: '6821',
    lineNumber: '6821-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'JD. JANGADEIRO',
    intermediateDestinations: ['MESTRAS', 'ITAPECERICA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2001',
    plate: 'CPB-6821',
    description: 'S21',
    history: 'Alimentadora TC.',
    viaSign: 'VIA MESTRAS',
  },
  {
    id: '6822',
    lineNumber: '6822-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'JD. MACEDÔNIA',
    intermediateDestinations: ['EST. ITAPECERICA', 'COHAB'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-6822',
    description: 'Alpha',
    history: 'Alimentadora TC.',
    viaSign: 'VIA MACEDÔNIA',
  },
  {
    id: '6823',
    lineNumber: '6823-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'JD. GUARUJÁ',
    intermediateDestinations: ['GUARAPIRANGA', 'M\'BOI MIRIM'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6823',
    description: 'S21',
    history: 'Via Guarujá.',
    viaSign: 'VIA M\'BOI',
  },
  {
    id: '6824',
    lineNumber: '6824-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'PQ. FERNANDA',
    intermediateDestinations: ['ITAPECERICA', 'COHAB'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-6824',
    description: 'S21',
    history: 'Alimentadora TC.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6825',
    lineNumber: '6825-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'VALO VELHO',
    intermediateDestinations: ['ITAPECERICA', 'COHAB'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6825',
    description: 'Apache Vip',
    history: 'Alimentadora TC.',
    viaSign: 'VIA ITAPECERICA',
  },
  {
    id: '6826',
    lineNumber: '6826-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'JD. STO. EDUARDO',
    intermediateDestinations: ['ITAPECERICA', 'UNASP'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2001',
    plate: 'TKB-6826',
    description: 'Pluss',
    history: 'Alimentadora TC.',
    viaSign: 'VIA UNASP',
  },
  {
    id: '6827',
    lineNumber: '6827-10',
    destination: 'VALO VELHO',
    secondaryDestination: 'TERM. CAPELINHA',
    intermediateDestinations: ['ITAPECERICA', 'COHAB'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6827',
    description: 'Apache',
    history: 'Rota alternativa Valo Velho.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6828',
    lineNumber: '6828-10',
    destination: 'COHAB ADVENTISTA',
    secondaryDestination: 'TERM. CAPELINHA',
    intermediateDestinations: ['ELLIS MAAS', 'ITAPECERICA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6828',
    description: 'Pluss',
    history: 'Alimentadora TC.',
    viaSign: 'VIA ELLIS MAAS',
  },
  {
    id: '6829',
    lineNumber: '6829-10',
    destination: 'JD. VAZ DE LIMA',
    secondaryDestination: 'TERM. CAPELINHA',
    intermediateDestinations: ['M\'BOI MIRIM', 'ITAPECERICA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6829',
    description: 'Vitória',
    history: 'Alimentadora TC.',
    viaSign: 'VIA M\'BOI',
  },
  {
    id: '6830',
    lineNumber: '6830-10',
    destination: 'JD. IRENE',
    secondaryDestination: 'TERM. CAPELINHA',
    intermediateDestinations: ['ITAPECERICA', 'COHAB'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-6830',
    description: 'S21',
    history: 'Jd. Irene x Capelinha.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6831',
    lineNumber: '6831-10',
    destination: 'JD. GUARUJÁ',
    secondaryDestination: 'TERM. CAPELINHA',
    intermediateDestinations: ['M\'BOI MIRIM', 'GUARAPIRANGA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2001',
    plate: 'CPB-6831',
    description: 'S21',
    history: 'Alimentadora TC.',
    viaSign: 'VIA M\'BOI',
  },
  {
    id: '6832',
    lineNumber: '6832-10',
    destination: 'PQ. ARARIBÁ',
    secondaryDestination: 'TERM. CAPELINHA',
    intermediateDestinations: ['CAMPO LIMPO', 'ITAPECERICA'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2003',
    plate: 'TKB-6832',
    description: 'Millennium',
    history: 'Araribá x Capelinha.',
    viaSign: 'VIA C. LIMPO',
  },
  {
    id: '6833',
    lineNumber: '6833-10',
    destination: 'JD. SÃO JOSÉ',
    secondaryDestination: 'TERM. CAPELINHA',
    intermediateDestinations: ['M\'BOI MIRIM', 'ITAPECERICA'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-6833',
    description: 'S21',
    history: 'Alimentadora TC.',
    viaSign: 'VIA M\'BOI',
  },
  {
    id: '6835-10',
    lineNumber: '6835-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'VALO VELHO',
    intermediateDestinations: ['ITAPECERICA', 'COHAB'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-6835',
    description: 'Apache',
    history: 'Principal ligação TC x Valo Velho.',
    viaSign: 'VIA ITAPECERICA',
  },
  {
    id: '6835-31',
    lineNumber: '6835-31',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'VALO VELHO',
    intermediateDestinations: ['DIRETO', 'COHAB'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-3531',
    description: 'Apache',
    history: 'Atendimento via Cohab.',
    viaSign: 'VIA COHAB',
  },
  {
    id: '6836',
    lineNumber: '6836-10',
    destination: 'TERM. CAPELINHA',
    secondaryDestination: 'CAPÃO REDONDO',
    intermediateDestinations: ['ITAPECERICA', 'METRÔ'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-6836',
    description: 'S21',
    history: 'Ligação curta ao Metrô.',
    viaSign: 'VIA METRÔ',
  },

  // 695x
  {
    id: '695R',
    lineNumber: '695R-10',
    destination: 'METRÔ JABAQUARA',
    secondaryDestination: 'JD. JANGADEIRO',
    intermediateDestinations: ['INTERLAGOS', 'SABARÁ', 'CUPECÊ'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2001',
    plate: 'CPB-695R',
    description: 'Millennium',
    history: 'Ligação perimetral Sul.',
    viaSign: 'VIA CUPECÊ',
  },
  {
    id: '695T',
    lineNumber: '695T-10',
    destination: 'VILA MARIANA',
    secondaryDestination: 'VALO VELHO',
    intermediateDestinations: ['STO. AMARO', 'DOMINGOS DE MORAIS'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2003',
    plate: 'TKB-695T',
    description: 'Millennium II',
    history: 'Troncal longa até o Metrô.',
    viaSign: 'VIA STO AMARO',
  },
  {
    id: '695V',
    lineNumber: '695V-10',
    destination: 'METRÔ ANA ROSA',
    secondaryDestination: 'VALO VELHO',
    intermediateDestinations: ['STO. AMARO', 'VERGUEIRO'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2003',
    plate: 'TKB-695V',
    description: 'Millennium II',
    history: 'Variante até Ana Rosa.',
    viaSign: 'VIA STO AMARO',
  },

  // 746x
  {
    id: '746A',
    lineNumber: '746A-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'JD. MACEDÔNIA',
    intermediateDestinations: ['CAMPO LIMPO', 'JOÃO DIAS'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '1999',
    plate: 'CPB-746A',
    description: 'Vitória',
    history: 'Ligação Macedônia x Sto Amaro.',
    viaSign: 'VIA C. LIMPO',
  },
  {
    id: '746C',
    lineNumber: '746C-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'CAMPO LIMPO',
    intermediateDestinations: ['JOÃO DIAS', 'CENESP'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-746C',
    description: 'Apache',
    history: 'Linha tradicional do Campo Limpo.',
    viaSign: 'VIA JOÃO DIAS',
  },
  {
    id: '746M',
    lineNumber: '746M-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'JD. M. SAMPAIO',
    intermediateDestinations: ['CAMPO LIMPO', 'JOÃO DIAS'],
    companyName: 'Transkuba',
    companyLogoText: 'TRANSKUBA',
    color: '#7f1d1d',
    year: '2002',
    plate: 'TKB-746M',
    description: 'Pluss',
    history: 'Maria Sampaio x Sto Amaro.',
    viaSign: 'VIA C. LIMPO',
  },
  {
    id: '746T',
    lineNumber: '746T-10',
    destination: 'SANTO AMARO',
    secondaryDestination: 'JD. TABOÃO',
    intermediateDestinations: ['VILA SÔNIA', 'JOÃO DIAS'],
    companyName: 'Viação Campo Belo',
    companyLogoText: 'CAMPO BELO',
    color: '#7f1d1d',
    year: '2000',
    plate: 'CPB-746T',
    description: 'Alpha',
    history: 'Taboão x Sto Amaro.',
    viaSign: 'VIA VILA SÔNIA',
  },

  // 775x
  {
    id: '775J',
    lineNumber: '775J-10',
    destination: 'METRÔ SÃO JUDAS',
    secondaryDestination: 'JD. DAS PALMAS',
    intermediateDestinations: ['VILA ANDRADE', 'JOÃO DIAS'],
    companyName: 'Viação Gatusa',
    companyLogoText: 'GATUSA',
    color: '#7f1d1d',
    year: '2003',
    plate: 'GTS-775J',
    description: 'Millennium',
    history: 'Perimetral Sudoeste.',
    viaSign: 'VIA GIOVANNI',
  },
  {
    id: '775J-23',
    lineNumber: '775J-23',
    destination: 'CAMPO BELO',
    secondaryDestination: 'JD. DAS PALMAS',
    intermediateDestinations: ['VILA ANDRADE', 'MORUMBI'],
    companyName: 'Viação Gatusa',
    companyLogoText: 'GATUSA',
    color: '#7f1d1d',
    year: '2003',
    plate: 'GTS-5J23',
    description: 'Millennium',
    history: 'Atendimento encurtado.',
    viaSign: 'VIA MORUMBI',
  }
];